version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - pnpm
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /server
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - server

  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - client

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - ci

  - package-ecosystem: docker
    directory: /server
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: /client
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - docker
